vich_uploader:
    db_driver: orm
    mappings:
        catalogue_pdfs:
            uri_prefix: /uploads/catalogues/pdf
            upload_destination: '%kernel.project_dir%/public/uploads/catalogues/pdf'
            namer: vich_uploader.namer_origname
            delete_on_update: true
            delete_on_remove: true
            
        catalogue_thumbnails:
            uri_prefix: /uploads/catalogues/thumbnails
            upload_destination: '%kernel.project_dir%/public/uploads/catalogues/thumbnails'
            namer: vich_uploader.namer_origname
            delete_on_update: true
            delete_on_remove: true






        