controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
category_show:
    path: /{slug}
    controller: App\Controller\CategoryController::show

